server:
  port: 10010
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    admin-service: /admin/**
    auth-service: /auth/**
  add-host-header: true
  sensitive-headers: